### ISSUE TITLE
Fatal error when accessing the order details tab in WooCommerce 3.0+

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/affiliatewp-order-details-for-affiliates#24]
Reported today by a customer: https://secure.helpscout.net/conversation/367404254/59533/?folderId=205529

```
Fatal error: Uncaught exception 'Exception' with message 'Invalid order.' in /path/to/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:86

Stack trace:
	#0 /path/to/woocommerce/includes/class-wc-data-store.php(143): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order))
	#1 /path/to/woocommerce/includes/abstracts/abstract-wc-order.php(109): WC_Data_Store->read(Object(WC_Order))
	#2 /path/plugins/affiliatewp-order-details-for-affiliates/includes/class-order-details.php(142): WC_Abstract_Order->__construct('1778')
	#3 /path/plugins/affiliatewp-order-details-for-affiliates/templates/dashboard-tab-order-details.php(40): AffiliateWP_Order_Details_For_Affiliates_Order_Details->get(Object(AffWP\Referral), 'order_number')
	#4 /home/wdnhaodt/public_html/wp-includes/template.php(686): require('/home/wdnhaodt/...')
	#5 /home/wdnhaodt/public_html in /path/to/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 86
```

**Comment by DrewAPicture** [comment]
PR: #25

**Comment by DrewAPicture** [comment]
As of e2db21967043e0a94f4c64cf72549a2003afb779, a message is now displayed if the exception is thrown and further output halted. This works in both pre- and post-WooCommerce 3.0.0. Looks like this:

![Order error](https://cl.ly/0R003h3o3U0X/Screen%20Shot%202017-05-18%20at%208.18.00%20PM.png)

**Comment by DrewAPicture** [comment]
Received confirmation from the customer that the fatal is now fixed as well.
